### ISSUE TITLE
Missing 'bs4' module in requirements.txt

### ISSUE THREAD

**Issue by w3bn00b3r** [anmolksachan/ThreatTracer#5]
Hi @anmolksachan 

Kindly mention 'bs4' in requirements.txt

![image](https://github.com/user-attachments/assets/1ec07379-47ac-4fed-bd53-73e43c2f9bec)

**Comment by anmolksachan** [comment]
updated the same in requirements.txt, do have a look and let me know If you have any questions/ concerns.
